# Generated by Django 2.2.6 on 2019-10-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='published',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
