# Generated by Django 2.2.6 on 2019-10-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_book_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='img_source',
            field=models.URLField(max_length=255),
        ),
    ]
