# Generated by Django 2.2.6 on 2019-10-20 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='book',
            field=models.ForeignKey(default=111, on_delete=django.db.models.deletion.CASCADE, to='catalog.Book'),
            preserve_default=False,
        ),
    ]
